config/routes.rb
Inquiry::Application.routes.draw do

  match "/results/confirm"  => "results#confirm"
  match "/results/complete" => "results#complete"

  resources :results do
  end

end

app/models/result.rb
class Result < ActiveRecord::Base
	validates :name,  :presence => true
	validates :mail,  :presence => true, :confirmation => true, :format => {:with=>/^[a-zA-z]+$/, :message=>"メールアドレスではありません"}
	validates :mail_confirmation, :presence => true
	validates :tel,   :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  # GET /results
  # GET /results.json
  def index
    @results = Result.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @results }
    end
  end

  # GET /results/1
  # GET /results/1.json
  def show
    @result = Result.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @result }
    end
  end

  # GET /results/new
  # GET /results/new.json
  def new
    @result = Result.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @result }
    end
  end

  # GET /results/1/edit
  def edit
    @result = Result.find(params[:id])
  end

  # GET /results/confirm
  def confirm
	@result = Result.new(params[:result])
    respond_to do |format|
      if @result.valid?
		# 確認画面
		format.html
        #format.html { redirect_to @result, :notice => 'こちらで保存します' }
        #format.json { render :json => @result, :status => :created, :location => @result }
      else
		# エラー
		#format.html
        format.html { render :action => "new" }
        #format.json { render :json => @result.errors, :status => :unprocessable_entity }
      end
    end
  end

  # /results/complete
  def complete
    @result = Result.new(params[:result])

    respond_to do |format|
      if @result.save
		 
		format.html {redirect_to :action => "index"}
		#format.html
        #format.html { redirect_to root_url, :notice => 'Result was successfully created.' }
        #format.html { redirect_to @result, :notice => 'Result was successfully created.' }
        #format.json { render :json => @result, :status => :created, :location => @result }
      else
        format.html { render :action => "new" }
        #format.json { render :json => @result.errors, :status => :unprocessable_entity }
      end
    end
  end

  # POST /results
  # POST /results.json
  def create
    @result = Result.new(params[:result])

    respond_to do |format|
      if @result.save
        format.html { redirect_to @result, :notice => 'Result was successfully created.' }
        format.json { render :json => @result, :status => :created, :location => @result }
      else
        format.html { render :action => "new" }
        format.json { render :json => @result.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /results/1
  # PUT /results/1.json
  def update
    @result = Result.find(params[:id])

    respond_to do |format|
      if @result.update_attributes(params[:result])
        format.html { redirect_to @result, :notice => 'Result was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @result.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.json
  def destroy
    @result = Result.find(params[:id])
    @result.destroy

    respond_to do |format|
      format.html { redirect_to results_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Inquiry</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/results/_confirm.html.erb
<%= form_for @result, :url => { :action => "complete" } do |f| %>
  <% if @result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% @result.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :mail %><br />
    <%= f.text_field :mail %>
  </div>
  <div class="field">
    <%= f.label :mail_confirmation %><br />
    <%= f.text_field :mail_confirmation %>
  </div>
  <div class="field">
    <%= f.label :tel %><br />
    <%= f.number_field :tel %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/results/_form.html.erb
<%= form_for @result, :url => { :action => "confirm" } do |f| %>
  <% if @result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% @result.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :mail %><br />
    <%= f.text_field :mail %>
  </div>
  <div class="field">
    <%= f.label :mail_confirmation %><br />
    <%= f.text_field :mail_confirmation %>
  </div>
  <div class="field">
    <%= f.label :tel %><br />
    <%= f.number_field :tel %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/results/complete.html.erb
<h1>完了画面</h1>

app/views/results/confirm.html.erb
<h1>確認画面</h1>

<%= render 'confirm' %>

app/views/results/edit.html.erb
<h1>Editing result</h1>

<%= render 'form' %>

<%= link_to 'Show', @result %> |
<%= link_to 'Back', results_path %>

app/views/results/index.html.erb
<h1>Listing results</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Mail</th>
    <th>Tel</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @results.each do |result| %>
  <tr>
    <td><%= result.name %></td>
    <td><%= result.mail %></td>
    <td><%= result.tel %></td>
    <td><%= result.body %></td>
    <td><%= link_to 'Show', result %></td>
    <td><%= link_to 'Edit', edit_result_path(result) %></td>
    <td><%= link_to 'Destroy', result, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Result', new_result_path %>

app/views/results/new.html.erb
<h1>New result</h1>

<%= render 'form' %>

<%= link_to 'Back', results_path %>

app/views/results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @result.name %>
</p>

<p>
  <b>Mail:</b>
  <%= @result.mail %>
</p>

<p>
  <b>Tel:</b>
  <%= @result.tel %>
</p>

<p>
  <b>Body:</b>
  <%= @result.body %>
</p>


<%= link_to 'Edit', edit_result_path(@result) %> |
<%= link_to 'Back', results_path %>